version: "3"

networks:
    nginx:
        external: true

services:
    nginx:
        image: nginx:alpine
        container_name: nginx-login-binaes
        ports:
            - 80:80
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/login-binaes:delegated
        depends_on:
            - php
        networks:
            nginx:
                aliases:
                    - nginx-login-binaes

    php:
        image: cyberduck/php-fpm-laravel:8.2
        container_name: php-login-binaes
        restart: always
        expose:
            - 9000
        volumes:
            - ./:/var/www/login-binaes:delegated
        networks:
            nginx:
                aliases:
                    - php-login-binaes

    composer:
        image: cyberduck/php-fpm-laravel:8.2
        container_name: composer
        volumes:
            - ./:/var/www/login-binaes
        working_dir: /var/www/login-binaes
        depends_on:
            - php
        entrypoint: [ "composer" ]
        networks:
            nginx:
                aliases:
                    - composer-login-binaes

    npm:
        image: node:18
        container_name: npm
        volumes:
            - ./:/var/www/login-binaes
        working_dir: /var/www/login-binaes
        entrypoint: [ "npm" ]
        networks:
            nginx:
                aliases:
                    - npm-login-binaes

    artisan:
        image: cyberduck/php-fpm-laravel:8.2
        container_name: artisan
        volumes:
            - ./:/var/www/login-binaes:delegated
        working_dir: /var/www/login-binaes
        entrypoint: [ "php", "/var/www/login-binaes/artisan" ]
        networks:
            nginx:
                aliases:
                    - artisan-login-binaes
